"""fixed admins table

Revision ID: 61ddd5de7539
Revises: 271cbcdce49a
Create Date: 2022-08-27 14:35:31.314952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ddd5de7539'
down_revision = '271cbcdce49a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
