"""fixed quiz3 table

Revision ID: 6997f0e16ba9
Revises: 72441b306e9e
Create Date: 2022-08-28 23:59:11.341125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6997f0e16ba9'
down_revision = '72441b306e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('questions_theme_id_key', 'questions', type_='unique')
    op.drop_constraint('themes_id_key', 'themes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('themes_id_key', 'themes', ['id'])
    op.create_unique_constraint('questions_theme_id_key', 'questions', ['theme_id'])
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
