"""fixed quiz3 table

Revision ID: 6bb8e1f06892
Revises: bda25b0a3b71
Create Date: 2022-08-28 21:44:50.176880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb8e1f06892'
down_revision = 'bda25b0a3b71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
