"""fixed quiz3 table

Revision ID: 72441b306e9e
Revises: 783be6bdf16f
Create Date: 2022-08-28 23:56:56.025712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72441b306e9e'
down_revision = '783be6bdf16f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'themes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    # ### end Alembic commands ###
