"""fixed quiz3 table

Revision ID: 783be6bdf16f
Revises: ad89c86d2899
Create Date: 2022-08-28 23:30:00.253296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783be6bdf16f'
down_revision = 'ad89c86d2899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['title'])
    op.create_unique_constraint(None, 'questions', ['theme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
