"""fixed quiz3 table

Revision ID: bda25b0a3b71
Revises: eee5d6423e3f
Create Date: 2022-08-28 21:30:47.374771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda25b0a3b71'
down_revision = 'eee5d6423e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
